# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0  # LTS
  - 1.3  # Latest release
  - nightly
arch:
  - x64
  - x86
env:
  global:
    - PYTHON=""
  matrix:
    - CONDA_JL_VERSION="3"  # Documentation stage will use the first variable set
    - CONDA_JL_VERSION="2"
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

  # Test 32-bit only on Linux
  exclude:
    - arch: x86
      os: osx
    - arch: x86
      os: windows

  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email:
    recipients:
      - nightly-dev@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
